### ISSUE TITLE
ansible-core recommends ansible

### ISSUE THREAD

**Issue by MarkusTeufelberger** [ansible-community/ppa#17]
If someone just wants to install ansible-core, having to turn of recommended packages is annoying.

Please move `ansible` from `Recommends` to something like `Suggests` in the `ansible-core` package. `ansible` already `Depends` on `ansible-core`, so if someone runs `apt install ansible-core` this is likely already intentional. `apt install ansible` is not impacted by this anyways.

**Comment by Ompragash** [comment]
@MarkusTeufelberger `ansible-core==2.12x` packages are updated to not include `ansible`! 
Please try and let me know how it goes.

**Comment by Ompragash** [comment]
@MarkusTeufelberger As the context of this issue is already implemented, I'll close this issue for now. Feel free to comment/re-open if you need more clarity on this.
