### ISSUE TITLE
ansible/ansible-4 PPA situation

### ISSUE THREAD

**Issue by rfdparker** [ansible-community/ppa#2]
It is suggested to not use the `ansible/ansible-4` PPA at this time?

Apologies for creating an issue for this to ask this question!

The `ansible/ansible-4` PPA currently provides Ansible 4.3.0, while `ansible/testing-ansible-4` currently provides Ansible 4.5.0.

#1 welcomes testers for `ansible/testing-ansible-4` but does not reference `ansible/ansible-4`.

Some while ago I came across the `ansible/ansible-4` PPA when looking on Launchpad at the old packages in the `ansible/ansible-4` PPA (that is still referenced by [the Ansible documentation](https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#installing-ansible-on-ubuntu)). I'm happy with the Ansible 4.3 (and `ansible-core` 2.11.3) packages it currently provides for `focal`, but it would be helpful to know whether or not it's due to be updated going forward.

Thanks to those involved in maintaining the PPAs.

**Comment by dericcrago** [comment]
hi @rfdparker - no worries about creating an issue, thanks for stopping by! 😄 I fell behind in my updating responsibilities (I'm actually trying to eliminate myself as a bottleneck for this going forward) and completely missed the `4.4.0` release. I just updated `ansible/testing-ansible-4` and `ansible/ansible-4` will be updated as well within the next 24 hrs. Going forward, the only differences between `testing-ansible-4` and `ansible-4` (for example) should be that `testing-ansible-4` will include test releases (alphas, betas, rcs) and might release ~24 hrs sooner.

**Comment by dericcrago** [comment]
`ansible 4.5.0` & `ansible-core 2.11.4` have been pushed to `ansible/ansible-4`! Thanks @rfdparker! Closing.

**Comment by rfdparker** [comment]
Thanks @dericcrago for the clarification and updates!
