### ISSUE TITLE
Missing PPA for Ubuntu Kinetic (22.10)

### ISSUE THREAD

**Issue by Iwifia** [ansible-community/ppa#28]
When runing an update you get the following

```
Err:12 https://ppa.launchpadcontent.net/ansible/ansible/ubuntu kinetic Release
  404  Not Found [IP: 185.125.190.52 443]
Reading package lists... Done                               
E: The repository 'https://ppa.launchpadcontent.net/ansible/ansible/ubuntu kinetic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

Any way around this until one is made?

**Comment by Ompragash** [comment]
@Iwifia Thanks for reporting this and the ETA for ansible, ansible-core availability on Ubuntu Kinetic will be available by the end of next week!

For now, you can try it on jammy using the below:
```
add-apt-repository ppa:ansible/testing-ansible-6
apt update
```

**Comment by Iwifia** [comment]
Is this still happening? I havent updated to the newest PPA yet.

**Comment by firefart** [comment]
> Is this still happening? I havent updated to the newest PPA yet.

jep, still resulting in a 404

**Comment by Iwifia** [comment]
> > Is this still happening? I havent updated to the newest PPA yet.
> 
> jep, still resulting in a 404

Yeah I saw that as well. I can't even remove it to use pip due to this lol.

**Comment by Ompragash** [comment]
@Iwifia @firefart Apologies for the late reply. Ansible is made available for Kinetic variants:

```
add-apt-repository ppa:ansible/testing-ansible-6
apt update
```

Kindly try and let me know how it goes.
