### ISSUE TITLE
Missing Lunar support

### ISSUE THREAD

**Issue by mishac** [ansible-community/ppa#43]
Looks like the ppa doesn't have a release file for lunar / 23.04

**Comment by mrveress** [comment]
Yep, waiting as well)

**Comment by dericcrago** [comment]
@mishac / @mrveress - lunar support has been added to the upcoming ansible 8 release, please try the following and create a new issue if you run into issues

`ppa:ansible/testing-ansible-8` OR `ppa:ansible/testing-ansible`
