### ISSUE TITLE
Unmet dependency python3-resolvelib on Debian 12

### ISSUE THREAD

**Issue by thgoebel** [ansible-community/ppa#55]
### Steps to reproduce

Just follow the instructions: https://docs.ansible.com/ansible/latest/installation_guide/installation_distros.html#installing-ansible-on-debian

1. Add the PPA to a sources.list: `deb http://ppa.launchpad.net/ansible/ansible/ubuntu jammy main`
2. `sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 93C4A3FD7BB9C367`
3. `sudo apt update`
4. `sudo apt install ansible`

Note that the instructions are missing a mapping from Debian 12 to an Ubuntu version. 22.04/jammy is an educated guess.

## Actual behaviour

```bash
$ sudo apt install ansible
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 ansible-core : Depends: python3-resolvelib (< 0.9.0) but 0.9.0-2 is to be installed
E: Unable to correct problems, you have held broken packages.
```

## Expected behaviour

It would be nice if this PPA would work on Debian 12 as well.

## Info

- Debian 12.0
- Related: #16

**Comment by Tecktron** [comment]
Having this same issue with Ubuntu 23.04

**Comment by thgoebel** [comment]
That PPA works on Debian 12 when using jammy. :tada:
It also works with Ubuntu 23.04 (using lunar obviously).
