### ISSUE TITLE
ansible-9 PPA

### ISSUE THREAD

**Issue by rfdparker** [ansible-community/ppa#80]
Please can a `ansible-9` PPA be provided?

So far the packages in `testing-ansible-9` seem to be working for me, thanks, and a non-`testing` equivalent would be much appreciated. I'm using `jammy` (Ubuntu 22.04 LTS).

**Comment by rfdparker** [comment]
Just to clarify, I can see a `ansible-9` PPA already exists but it currently appears to contain no packages.

**Comment by alexcernat** [comment]
+1, a "stable" ansible-9 repo would be appreciated
